### ISSUE TITLE
Building KIAH George Bush Intercontinental Airport

### ISSUE THREAD

**Issue by david-garza** [EndlessATC/Airports#180]
I just recently purchased Endless ATC and wanted to play my local airports. I found that someone already started a KIAH file. I have been working on it the last few days. I am setting up the scenario for a calm / prevailing winds traffic flows for both KIAH and KHOU.

**Comment by AdamJCavanaugh** [comment]
Sounds good, thanks!

**Comment by david-garza** [comment]
branch merged into main
