### ISSUE TITLE
LSZH unrealistic

### ISSUE THREAD

**Issue by Daddelhai** [EndlessATC/Airports#183]
LSZH has wrong runway concepts, the MRVAs are not implemented, SIDs and STARs are missing. Rwy 28 and 34 have the wrong glide slope (3.0 instead of 3.3)

Runway concepts at LSZH:
- ARR 14 / DEP 28 SEC 16 (day concept)
- ARR 14 / DEP 10 SEC 16 (day concept, alternative, active when tailwind of 28 greater than 10kt)
- ARR 28 (34 on request) / DEP 32 SEC 34 (evening concept as german airspace is closed after 2200lcl)
- ARR 34 / DEP 32 SEC 34 (28 on request) (morning concept)

**Comment by AdamJCavanaugh** [comment]
[lszh.txt](https://github.com/EndlessATC/Airports/files/7952859/lszh.txt)

Does this file from dunne_boktor address your concerns okay?
