### ISSUE TITLE
KJFK

### ISSUE THREAD

**Issue by CessnaSkyhawk** [EndlessATC/Airports#211]
KJFK and KFRG

**Comment by AdamJCavanaugh** [comment]
There have been no comments or work on this for 20 days. After 30 days of inactivity, the issue will be closed. The issue can be reopened later if new work is available.

**Comment by CessnaSkyhawk** [comment]
I've decided to close this issue. I have multiple updates to different airports that have all accidentally gotten mixed together so I don't want to screw thins up or overwrite other people's work. Will open a new PR once everything is sorted
