### ISSUE TITLE
KLGA

### ISSUE THREAD

**Issue by CessnaSkyhawk** [EndlessATC/Airports#213]
My take on LGA, alongside HPN and DXB

**Comment by TheArlan** [comment]
Its been two week now‚ and no update. But i still waiting for the release‚ i frequently checked this github all day long but no new airport files.

**Comment by CessnaSkyhawk** [comment]
@TheArlan I have other real-life commitments which get in the way. Please be patient and it will be released eventually.

**Comment by AdamJCavanaugh** [comment]
There have been no comments or work on this for 20 days. After 30 days of inactivity, the issue will be closed. The issue can be reopened later if new work is available.

**Comment by CessnaSkyhawk** [comment]
I've decided to close this issue. I have multiple updates to different airports that have all accidentally gotten mixed together so I don't want to screw thins up or overwrite other people's work. Will open a new PR once everything is sorted
