### ISSUE TITLE
I created custom airport file for RPVM

### ISSUE THREAD

**Issue by brcklpz** [EndlessATC/Airports#230]
I created a custom file for RPVM with SID's and STAR's. it is already done and working

**Comment by TheArlan** [comment]
When you will release the file?

**Comment by TheArlan** [comment]
When you will release the file?

**Comment by brcklpz** [comment]
I want to release it now but I cant understand how

**Comment by TheArlan** [comment]
Maybe you should open pull requests

**Comment by TheArlan** [comment]
Or if you want the advanced guide:

1. Open an issue describing the work you want to do (or want done, but it will be faster if you participate!)
2. Fork this repository
3.Clone your fork to your computer so you can work on it
4. Set this repository to be the upstream repository of your fork
5. Ensure your repository has the most recent changes from upstream
6. Create a branch in your repository: git checkout -b iss#/desc where the open issue and description are both included
7. Make local changes until your repository contains all completed work
8. Commit your changes: git commit -am 'iss#/desc - closes iss#' Use keywords to assist with linking issues and pull requests
9. Push to your branch: git push origin iss#/desc
10. Submit a pull request from your fork to the upstream repository

**Comment by brcklpz** [comment]
idk how to use git, im just new here

**Comment by TheArlan** [comment]
Maybe you could ask a person (in discord)‚ how to use github. In Endless ATC discord server if you want to ask something like question or etc‚ go to #general channel.

**Comment by TheArlan** [comment]
Or just dm a person in discord
