### ISSUE TITLE
Is there no new airport files again now?

### ISSUE THREAD

**Issue by TheArlan** [EndlessATC/Airports#242]
Is there no new airport files again now? it's been 20 days now since 13 june

**Comment by AdamJCavanaugh** [comment]
What is this in regards to? All current airport files are available in the appropriate location under the "final" directory.

**Comment by TheArlan** [comment]
Yeah i think this github is dead.... But after reinstalling my discord again and join the Endless ATC server.... Boom! There is so many activity in the past month

**Comment by AdamJCavanaugh** [comment]
Yes, the Discord is definitely active. The GitHub is only intended to contain finalized airports that authors wish to share with others, so it will always be a smaller subset of what's on the Discord.

Enjoy!
