### ISSUE TITLE
LFPG - Intersecting arrival paths

### ISSUE THREAD

**Issue by pos-ki** [EndlessATC/Airports#290]
On LFPG, arrivals to LFPO inbound VEBEK at FL130 often create separation incidents with LFPG arrivals inbound LORNI, as those "spawn" at slightly higher altitudes before descending to the set FL110.  

My proposed solution would be to spawn LFPO VEBEK arrivals at FL140-150, and make them descent to FL130 at VEBEK as part of the approach to keep the (I assume real life based) altitude.  

In the case the author does not maintain the file anymore, I would be happy to make the adjustment, if the change is agreed on.

**Comment by AdamJCavanaugh** [comment]
I have no record or history of the author of that file, so feel free to make the change yourself, thanks!

**Comment by pos-ki** [comment]
I haven't quite been able to get myself to make that particular tweak - I do, however, have my own file that I use, which has the entry altitudes significantly increased, and descent profiles implemented, with few other tweaks and additions. With adjusting the entry altitudes, the problem of the intersecting arrival paths is also fixed.

**Comment by AdamJCavanaugh** [comment]
Perhaps place it as final/EU/LFPG_pos-ki.txt (or similar name)
