### ISSUE TITLE
Reworked LOWW

### ISSUE THREAD

**Issue by pos-ki** [EndlessATC/Airports#299]
I have my own version of LOWW almost ready for release (will probably be done within a week), build from scratch following the current AIP closely. It includes approaches and SIDs to/from all runways, with realistic airspace boundaries (TMAs) and current airlines (not perfect, but quite decent).

My only concern is whether I should replace the current file, or upload it alongside it like I did with LFPG.

**Comment by AdamJCavanaugh** [comment]
With no recent updates, I'd be content if you replaced the file, but it's your choice.
